extends:
  - airbnb-base
  - prettier
globals:
  beforeEach: true
  describe: true
  expect: true
  test: true
  jest: true
rules:
  import/prefer-default-export: off
  no-plusplus: off
  no-self-compare: off
  no-underscore-dangle:
    - error
    - allow:
        - __resolveReference
        - _embedded
