extends:
  - airbnb-base
  - prettier
globals:
  expect: true
  describe: true
  it: true
  jest: true
  beforeEach: true
rules:
  no-plusplus: off
  no-underscore-dangle:
    - error
    - allow:
        - __resolveReference
        - _embedded
  import/prefer-default-export: off
