extends:
  - airbnb
env:
  browser: true
  es6: true
  node: true
  mocha: true
globals:
  Atomics: readonly
  SharedArrayBuffer: readonly
parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: 2018
  sourceType: module
plugins:
  - react
rules:
  no-plusplus: off
  no-underscore-dangle:
    - error
    - allow:
        - __resolveReference
