export default {
  1: {
    locale: 'sv-tcne',
    longFormat: 'ddd D MMM Y',
    longNoDayFormat: 'D MMM Y',
    shortFormat: 'Y-MM-DD',
    dayFormat: 'D',
    timeFormat: 'HH:mm',
    monthShortNameFormat: 'MMM',
    dayMonthYearFormat: 'D MMM Y',
  },
  3: {
    locale: 'nb-tcne',
    longFormat: 'ddd D MMM Y',
    longNoDayFormat: 'D MMM Y',
    shortFormat: 'DD.MM.Y',
    dayFormat: 'D.',
    timeFormat: 'HH:mm',
    monthShortNameFormat: 'MMM.',
    dayMonthYearFormat: 'D MMM Y',
  },
  11: {
    locale: 'da-tcne',
    longFormat: 'ddd D MMM Y',
    longNoDayFormat: 'D MMM Y',
    shortFormat: 'DD-MM-Y',
    dayFormat: 'D',
    timeFormat: 'HH:mm',
    monthShortNameFormat: 'MMM',
    dayMonthYearFormat: 'D MMM Y',
  },
  15: {
    locale: 'fi-tcne',
    longFormat: 'ddd D.M.Y',
    longNoDayFormat: 'D.M.YYYY',
    shortFormat: 'D.M.Y',
    dayFormat: 'D',
    timeFormat: 'H:mm',
    monthShortNameFormat: 'MMM',
    dayMonthYearFormat: 'D MMM Y',
  },
  18: {
    locale: 'sv-tcne',
    longFormat: 'ddd D MMM Y',
    longNoDayFormat: 'D MMM Y',
    shortFormat: 'Y-MM-DD',
    dayFormat: 'D',
    timeFormat: 'HH:mm',
    monthShortNameFormat: 'MMM',
    dayMonthYearFormat: 'D MMM Y',
  },
};